export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const PATCH_ARTICLE = "PATCH_ARTICLE";

export const GET_SUBJECT = "GET_SUBJECT";
export const CREATE_SUBJECT = "CREATE_SUBJECT";

export const CREATE_SNNIPET = "CREATE_SNNIPET";
export const PATCH_SNNIPET = "PATCH_SNNIPET";
