# Generated by Django 2.2.4 on 2019-08-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webTemplate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='owner',
        ),
    ]
